# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: automatic_annotator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='automatic_annotator.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19\x61utomatic_annotator.proto\"3\n\x0f\x41nnotateRequest\x12\x10\n\x08\x64\x61tapath\x18\x01 \x01(\t\x12\x0e\n\x06\x65xpath\x18\x02 \x01(\t\"G\n\x10\x41nnotateResponse\x12\x10\n\x08imgpaths\x18\x01 \x03(\t\x12!\n\rall_proposals\x18\x02 \x03(\x0b\x32\n.Proposals\")\n\tProposals\x12\x1c\n\tproposals\x18\x01 \x03(\x0b\x32\t.Proposal\":\n\x08Proposal\x12\n\n\x02x1\x18\x01 \x01(\x05\x12\n\n\x02y1\x18\x02 \x01(\x05\x12\n\n\x02x2\x18\x03 \x01(\x05\x12\n\n\x02y2\x18\x04 \x01(\x05\x32?\n\x0c\x41utoAnnotate\x12/\n\x08\x41nnotate\x12\x10.AnnotateRequest\x1a\x11.AnnotateResponseb\x06proto3')
)




_ANNOTATEREQUEST = _descriptor.Descriptor(
  name='AnnotateRequest',
  full_name='AnnotateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datapath', full_name='AnnotateRequest.datapath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expath', full_name='AnnotateRequest.expath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=80,
)


_ANNOTATERESPONSE = _descriptor.Descriptor(
  name='AnnotateResponse',
  full_name='AnnotateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='imgpaths', full_name='AnnotateResponse.imgpaths', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='all_proposals', full_name='AnnotateResponse.all_proposals', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=153,
)


_PROPOSALS = _descriptor.Descriptor(
  name='Proposals',
  full_name='Proposals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposals', full_name='Proposals.proposals', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=196,
)


_PROPOSAL = _descriptor.Descriptor(
  name='Proposal',
  full_name='Proposal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x1', full_name='Proposal.x1', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y1', full_name='Proposal.y1', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x2', full_name='Proposal.x2', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y2', full_name='Proposal.y2', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=256,
)

_ANNOTATERESPONSE.fields_by_name['all_proposals'].message_type = _PROPOSALS
_PROPOSALS.fields_by_name['proposals'].message_type = _PROPOSAL
DESCRIPTOR.message_types_by_name['AnnotateRequest'] = _ANNOTATEREQUEST
DESCRIPTOR.message_types_by_name['AnnotateResponse'] = _ANNOTATERESPONSE
DESCRIPTOR.message_types_by_name['Proposals'] = _PROPOSALS
DESCRIPTOR.message_types_by_name['Proposal'] = _PROPOSAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnnotateRequest = _reflection.GeneratedProtocolMessageType('AnnotateRequest', (_message.Message,), {
  'DESCRIPTOR' : _ANNOTATEREQUEST,
  '__module__' : 'automatic_annotator_pb2'
  # @@protoc_insertion_point(class_scope:AnnotateRequest)
  })
_sym_db.RegisterMessage(AnnotateRequest)

AnnotateResponse = _reflection.GeneratedProtocolMessageType('AnnotateResponse', (_message.Message,), {
  'DESCRIPTOR' : _ANNOTATERESPONSE,
  '__module__' : 'automatic_annotator_pb2'
  # @@protoc_insertion_point(class_scope:AnnotateResponse)
  })
_sym_db.RegisterMessage(AnnotateResponse)

Proposals = _reflection.GeneratedProtocolMessageType('Proposals', (_message.Message,), {
  'DESCRIPTOR' : _PROPOSALS,
  '__module__' : 'automatic_annotator_pb2'
  # @@protoc_insertion_point(class_scope:Proposals)
  })
_sym_db.RegisterMessage(Proposals)

Proposal = _reflection.GeneratedProtocolMessageType('Proposal', (_message.Message,), {
  'DESCRIPTOR' : _PROPOSAL,
  '__module__' : 'automatic_annotator_pb2'
  # @@protoc_insertion_point(class_scope:Proposal)
  })
_sym_db.RegisterMessage(Proposal)



_AUTOANNOTATE = _descriptor.ServiceDescriptor(
  name='AutoAnnotate',
  full_name='AutoAnnotate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=258,
  serialized_end=321,
  methods=[
  _descriptor.MethodDescriptor(
    name='Annotate',
    full_name='AutoAnnotate.Annotate',
    index=0,
    containing_service=None,
    input_type=_ANNOTATEREQUEST,
    output_type=_ANNOTATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AUTOANNOTATE)

DESCRIPTOR.services_by_name['AutoAnnotate'] = _AUTOANNOTATE

# @@protoc_insertion_point(module_scope)
